kind: Service
apiVersion: v1
metadata:
  name: person-api-service
spec:
  type: NodePort
  selector:
    app: person-api
  ports:
  - protocol: TCP
    port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-api-deploy
  labels:
    app: person-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: person-api
  template:
    metadata:
      labels:
        app: person-api
    spec:
      containers:
      - name: person-api
        image: sh4sh/sh4shtakehome:latest
        ports:
        - containerPort: 8080
